version: '3'

services:
  pgsql_db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=slowdash
      - POSTGRES_PASSWORD=slowdash
      - POSTGRES_DB=SlowTestData


  influxdb:
    image: influxdb:2
    restart: always
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=slowdash
      - DOCKER_INFLUXDB_INIT_PASSWORD=slowdash
      - DOCKER_INFLUXDB_INIT_ORG=sloworg
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=slowtoken
      - DOCKER_INFLUXDB_INIT_BUCKET=SlowTestData


  redis:
    image: redis/redis-stack:7.2.0-v10
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
